name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: self-hosted
    steps:
      - name: echo a string
        run: echo "Hi guys!"
  fail-shell-command:
    runs-on: self-hosted
    steps:
      - name: echo will fail
        run: eccho "Wassup"
